---

apiVersion: 'cert-manager.io/v1'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme:
    email: 'josh.walwyn@gmail.com'

---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'ingress-certificate'
spec:
  commonName: 'dev-location-events-api.proj.shw.al'
  dnsNames:
    - 'dev-location-events-api.proj.shw.al'
