---

apiVersion: 'cert-manager.io/v1'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme: null
  selfSigned: {}

---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'ingress-cert'
spec:
  commonName: 'lea-dev.proj.shw.al'
  dnsNames:
    - 'lea-local'
