---

apiVersion: 'cert-manager.io/v1'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme:
    email: 'me@joshwalwyn.com'

---

apiVersion: 'cert-manager.io/v1'
kind: 'Certificate'
metadata:
  name: 'ingress-certificate'
spec:
  commonName: 'location-events-api.proj.shw.al'
  dnsNames:
    - 'location-events-api.proj.shw.al'
