apiVersion: 'kustomize.config.k8s.io/v1beta1'
kind: 'Kustomization'

resources:
  - './certificates.yaml'
  - './deployment.yaml'
  - './ingress.yaml'

patchesStrategicMerge:
  - './patches/local.yaml'
