name: 'Infrastructure'

on:
  push:
    paths:
      - 'k8s/**'
      - 'tf/**'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Run ShellCheck'
        uses: 'ludeeus/action-shellcheck@master'
        with:
          scandir: './k8s'
  kubeconform:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'docker://ghcr.io/yannh/kubeconform:v0.5.0'
        with:
          entrypoint: '/kubeconform'
          args: >
            -verbose -debug
            -schema-location default
            -schema-location "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"
            -ignore-filename-pattern ".*(\/patches\/|kustomization).*"
            -summary
            -output json
            ./k8s
